server:
  #port: 8084
  port: 8084
spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://localhost:3306/vue?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
      username: root
      password: admin
      driver-class-name: com.mysql.cj.jdbc.Driver
      type : com.alibaba.druid.pool.DruidDataSource
    slave1:
      jdbc-url: jdbc:mysql://localhost:3306/vue?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
      username: root   # 只读账户
      password: admin
      driver-class-name: com.mysql.cj.jdbc.Driver
      type : com.alibaba.druid.pool.DruidDataSource
    slave2:
      jdbc-url: jdbc:mysql://localhost:3306/vue?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
      username: root   # 只读账户
      password: admin
      driver-class-name: com.mysql.cj.jdbc.Driver
      type : com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
      cache: false
      prefix: classpath:/templates/
      suffix: .html
      encoding: UTF-8
  resources:
    static-locations: classpath:/templates/,classpath:/static/


# Redis数据库索引（默认为0）
spring.redis.database: 0
# Redis服务器地址
spring.redis.host: 192.168.0.56
# Redis服务器连接端口
spring.redis.port: 6379
# Redis服务器连接密码（默认为空）
spring.redis.password:
# 连接池最大连接数（使用负值表示没有限制）
spring.redis.pool.max-active: 200
# 连接池最大阻塞等待时间（使用负值表示没有限制）
spring.redis.pool.max-wait: -1
# 连接池中的最大空闲连接
spring.redis.pool.max-idle: 10
# 连接池中的最小空闲连接
spring.redis.pool.min-idle: 0
# 连接超时时间（毫秒）
spring.redis.timeout: 3000

#thymeleaf start  org.springframework.boot.autoconfigure.thymeleaf.ThymeleafProperties
#spring.thymeleaf.mode: HTML5
#spring.thymeleaf.encoding: UTF-8
#spring.thymeleaf.content-type: text/html
#开发时关闭缓存,不然没法看到实时页面
#spring.thymeleaf.cache: false
#thymeleaf end


#server.tomcat.uri-encoding: utf-8




#spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
#spring.datasource.url: jdbc:mysql://localhost:3306/vue?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#spring.datasource.username: root
#spring.datasource.password: admin
#spring.datasource.max-idle: 10
#spring.datasource.max-wait: 10000
#spring.datasource.min-idle: 5
#spring.datasource.initial-size: 5

author:
 name: 邓秋
 csdnUrl: baidu.com


mybatis:
    #  mapper文件
    #mapper-locations: classpath:mapper/**/*Mapper.xml
    # 加载全局的配置文件
    config_location: classpath:/mybatis-config.xml
    #  实体类
    #type-aliases-package: com.example.entity


# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  pageSizeZero: false #pageSize=0

# 日志配置
logging:
  level:
    #com.example: debug
    org.springframework: WARN
    org.spring.springboot.dao: debug
    com.example.service.dao: debug








